### PR TITLE
Introduction of the shared folder and cleanup

### LINKED ISSUE #1: Moved shared files to shared folder, in root dir, and symlink
There are numerous files that have the same content but are copied into each example dir. This is because we want all relevant files for a run to be in one directory. 

To make things more maintainable we should create a shared folder in which we keep these files and then create symlinks into each example.

### PR DESCRIPTION
**Pull request by ribalba**
Closes #1

### CODE REVIEW

**Comment by ribalba** [comment]
Found a bug. Please don't merge

**Comment by ArneTR** [comment]
Nice idea with using relative paths instead of using actual symlinks, I believe this makes the folder structure much more clearer!

I also had a thought over the weekend which we might incorporate here:

I believe we might run into issues at some point due to the current auto naming when we build the images with `docker compose build`

*stress_stress* is neither very unique nor descriptive.

With the docker compose file format version 2 we can actually specify an image name.

An example would look like this:

```
version: '2'

services:
  stress:
    build:
      context: ../shared/stress
    image: gcb_stress
    container_name: gcb_stress
    restart: always
````

I also renamed the container to be the same name as the image, to reduce the plurality of differnent names floating around. If we have multiple instances of an image I would go for gcb_stress_1 _2 _3 ...

d'you have any experience with version format 2 and if it is the current standard? Or are people still using format 1 and this might hinder reusability?

**Comment by ribalba** [comment]
Hey,

there is a ticket [1] for this. I just haven't had time to do it. But I can add it to the PR. I think we should use version 2 at least in the examples. 

[1] https://github.com/green-coding-berlin/example-applications/issues/2

**Comment by ArneTR** [comment]
I see, that makes sense. Let's keep both tickets open then and Danilo shall be working on this during his onboarding.

**Comment by djesic** [comment]
All images created by the examples are now prefixed with `gcb` (Green Coding Berlin) and use a snake case naming convention.
This branch has been updated with the smoke tests that were merged into main as part or #14 
Some minor fixes for failing tests to come.

**Comment by djesic** [comment]
Closes #2 and #16
Current state of examples ran through smoke tests locally report the `blauer engel` is failing due to exceeding runtime (30m was latest attempt) and `wordpress-minimal` failing due to being unable to copy file an `.sql` file with relative path in `usage-scenario.yml`

**Comment by ArneTR** [comment]
@ribalba This task must be discussed again, as the shared setup how we want it is not really working.

Dream would be:
- Every subfolder that shares a common Dockerfile or common compose.yml will just symlink it.
  + This however is not possible as in the compose.yml the path is always relative to the folder where the command was called from!
  + a `build .` will then result in the wrong folder
  + Always assuming that any symlinked files will only be in a one folder up sibling is also too flaky `build ../shared/stress`
- Only solution as I see it for the moment is to alter the Readme to always call: `docker compose -f ../shared/stress/compose.yml` build

Open for discussion on Wednesday

**Comment by ArneTR** [comment]
As discussed we are now using the shared files in the appropriate shared folder and rather reference a call from the README how to `compose up` / `compose build` it

**Comment by ArneTR** [comment]
Has already been merged in https://github.com/green-coding-berlin/example-applications/commit/c89d876fd11e0d40b6d4db102d150e5190bf72d0

**Pull request closed without merging**
