### PR TITLE
Drupal example

### PR DESCRIPTION
**Pull request by marvil07-adapt**
An example with a base Drupal, following the idea and even content from the equivalent Wordpress example, so they are analogous.

### CODE REVIEW

**Comment by ArneTR** [comment]
Hey @marvil07-adapt 
big THX for the example application!

I have given it a spin and the results are here: https://metrics.green-coding.berlin/stats.html?id=51105930-051e-4f6c-abbf-a83483c21155

Can you give it a look? From my side it looks very good. But are the values what you are expecting? Duration for the runtime phase is 41s

Out of curiosity:
- How did you get aware of our tool? 
- Are you already using it locally / internally?

As you might guess we are super interested how people are using the Green Metrics Tool :)

**Comment by marvil07-adapt** [comment]
@ArneTR,

> big THX for the example application!

Oh, thanks for starting the green metrics tool project!
I find its approach quite interesting.

> I have given it a spin and the results are here: https://metrics.green-coding.berlin/stats.html?id=51105930-051e-4f6c-abbf-a83483c21155
> 
> Can you give it a look? From my side it looks very good. But are the values what you are expecting? Duration for the runtime phase is 41s

:+1: Thanks for running it there!

The results there look consistent with the ones I executed locally.
The run I made was on a quite smaller computer, hence numbers are different, but seems like the patterns of usage are mainly similar.
Sadly, I do not have any of the specific equipment for overall machine power measurement, only RAPL.

_Tangentially_, on the original version, before the phased changes introduced for v0.15, I was able to see overall metrics with RAPL.
After the changes for the phased approach, I see the RAPL metrics there, but the "Machine Power" and derived metrics are not anymore there.
I am wondering if there is a "psu" provider that uses RAPL, or if that is even sensible :sweat_smile:.
I am guessing that metrics on RAPL are not translatable to overall machine usage, and hence those are not calculated.
Also, when I use a synthetic psu metric provider like sdia, I still do not see overall numbers on machine power after providing the configuration for the used cpu.
Any hints will be welcomed, and I would also be happy to move this tangent into a different thread/place.

> Out of curiosity:
> 
> - How did you get aware of our tool?

I arrived to the video of your presentation at FOSDEM this year.
It was quite informative, and though provoking :+1:

> - Are you already using it locally / internally?

I am testing several things, to try to find a good set of tooling that may help provide a sense of resources usage.
To provide some extra background, this happens in the context of trying to align with UN sustainable development goals like [Affordable and clean enery](https://sdgs.un.org/goals/goal7), from our software industry.
Keeping track of data, in this case, energy consumption, is the first step towards more efficient use of resources.

Thanks again for starting this project!

**Comment by ArneTR** [comment]
The overall metrics before the 0.15 version where maybe a bad wording. RAPL can only provide some domains like CPU, DRAM, onboard-GPU and on some rare platforms als PSYS, which can technically include stuff like the chipset and maybe even monitor on laptops (not verfied to my knowledge).
Thus there is no PSU provider that uses RAPL.

In any case, our tool was never querying more than the CPU and DRAM domains ... so maybe this was just a bad wording from our side in the old UI.


If you attach an estimation reporter like XGBOOST or SDIA it should show in the machine power box .... does the machine power show at all for XBGOOST / SDIA if you open the detailed metrics?

Screenshot 2023-06-15 at 1 23 54 PM

**Comment by marvil07-adapt** [comment]
@ArneTR,

> The overall metrics before the 0.15 version where maybe a bad wording. RAPL can only provide some domains like CPU, DRAM, onboard-GPU and on some rare platforms als PSYS, which can technically include stuff like the chipset and maybe even monitor on laptops (not verfied to my knowledge).
> Thus there is no PSU provider that uses RAPL.
> 
> In any case, our tool was never querying more than the CPU and DRAM domains ... so maybe this was just a bad wording from our side in the old UI.

That makes sense, thanks for the extra context there :+1:

> If you attach an estimation reporter like XGBOOST or SDIA it should show in the machine power box .... does the machine power show at all for XBGOOST / SDIA if you open the detailed metrics?

Currently, I have not been able to see it there.
Given this is getting a bit off-topic, I opened an issue specifically about what I am testing at https://github.com/green-coding-berlin/green-metrics-tool/issues/327
We may want to continue the conversation about this bit there.

**Comment by ArneTR** [comment]
@dan-mm This PR is now ready to be merged. Please schedule that in for next week incl. the fix for the current Github Pipeline of the Example applications

**Pull request merged**
