### PR TITLE
Shows how to include a compose.yml

### PR DESCRIPTION
**Pull request by ribalba**

### CODE REVIEW

**Comment by ArneTR** [comment]
I slimmed down the example even further. It is okay if the network definitions are in the compose file

**Comment by ribalba** [comment]
I put them in the usage file on purpose to show how you can "overwrite" things. Because the compose might not come with a network specified and like this you can overwrite values to make it work.

**Comment by ribalba** [comment]
@ArneTR I don't know if you get notified if I comment like this? Do I need a @ArneTR ?

**Comment by ArneTR** [comment]
Tagging me always helps.

I see the reason now for this stucturing. I did not understand the decision just from reading the file though. 
I think we should re-use as much as possible in our examples to showcase how low the overhead is and then also have one specific example in the example-applications that specifically overwrites  something (actually only a merge ... or? You cannot really overwrite something atm ...?)

**Pull request merged**
